name: Report an Issue
description: Please provide a clear and concise description of what the issue is
title: "[ISSUE]: "
labels: ["bug"]
assignees: ["eistrati"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report.
        Make sure there aren't any open/closed issues for this topic
        
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Issue
      description: |
        Please provide a clear and concise description of what the issue is.
        note: for support questions, please use stackoverflow
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the behavior.
        If applicable, add screenshots to help explain your problem
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Add any other context about the problem here
