name: Request a Feature
description: Please provide a clear and concise description of what the feature is
labels: ["enhancement"]
title: "[FEATURE]: "
assignees: ["eistrati"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature report.
        Make sure there aren't any open/closed issues for this topic
  
  - type: textarea
    id: description
    attributes:
      label: Describe the Feature
      description: |
        Provide a brief description of the feature or enhancement
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Add any other context about the problem here
